spring.application.name=urban-furniture-accounting

spring.datasource.url=jdbc:mysql://localhost:3306/urban_furniture
spring.datasource.username=root
spring.datasource.password=Sneha$13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
