spring.application.name=urban-furniture-accounting
firebase.project-id=odoo-4116c
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/urban_furniture
spring.datasource.username=root
spring.datasource.password=parth2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
