app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

spring.datasource.url=jdbc:h2:file:./data/urban_furniture_local;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=parth2006
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
