spring.datasource.url=jdbc:h2:file:./data/urban_furniture_local;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
